let frase = [
    "Feliz aquele que transfere o que sabe e aprende o que ensina.",
    "Aos professores, que com empenho se dedicam à arte de ensinar, um agradecimento cheio de carinho!",
    "Heróis de verdade não vestem capas, eles ensinam.",
    "A mais bela profissão é aquela que faz os jovens alcançarem voos em direção ao futuro.",
    "O educador se eterniza em cada ser que ele educa.",
    "Parabéns, professores! Vocês são valorosos e essenciais para o mundo.",
    "Professor, uma profissão! Educador, a mais nobre de todas as missões.",
    "Um (a) professor (a) estende as mãos, abre mentes e toca corações.",
    "Educar é impregnar de sentido o que fazemos a cada instante.",
    "A influência de um bom professor jamais poderá ser apagada.",
    "Feliz dia do: “Copiem logo, que daqui a pouco estou apagando!",
    "A prova é em dupla? — Sim, você e sua consciência.",
    "Como as palavras não são suficientes… coloquei aqui todo o meu amor para você!",
    "Tirei 3,5 e o professor não quis arredondar pra 9,0. Gente, o que custa?",
    "Retribuímos mal a um professor se continuamos apenas alunos.",
    "O professor deve ser como um jardineiro, providenciar as melhores condições externas para que as plantas sigam seu desenvolvimento natural. Afinal, a semente traz em si o projeto da árvore toda.",
    "A excelência é um professor melhor que a mediocridade. As lições do comum estão em toda a parte. Percepções verdadeiramente profundas e originais só podem ser encontradas ao estudarmos o exemplar.",
    "A relação ideal entre professor e aluno existe quando o aluno é melhor que o professor.",
    "A missão do professor não é dar respostas prontas. As respostas estão nos livros, estão na Internet. A missão dos professores é provocar a inteligência, é provocar o espanto, a curiosidade.",
    "Fala com sabedoria e ensina com amor.",
    "O ensino dos sábios é fonte de vida e afasta o homem das armadilhas da morte.",
    "Todo aquele que não permanece no ensino de Cristo, mas vai além dele, não tem Deus; quem permanece no ensino tem o Pai e também o Filho.",
    "Apegue-se à instrução, não a abandone; guarde-a bem, pois dela depende a sua vida. Não siga pela vereda dos ímpios nem ande no caminho dos maus.",
    "Os conselhos são importantes para quem quiser fazer planos, e quem sai à guerra precisa de orientação.",
    "Toda a Escritura é inspirada por Deus e útil para o ensino, para a repreensão, para a correção e para a instrução na justiça, para que o homem de Deus seja apto e plenamente preparado para toda boa obra.",
    "Pois tudo o que foi escrito no passado foi escrito para nos ensinar, de forma que, por meio da perseverança e do bom ânimo procedentes das Escrituras, mantenhamos a nossa esperança.",
    "Ouça conselhos e aceite instruções, e acabará sendo sábio.",
    "Professor, te desejamos o salário de um deputado e o prestígio de um jogador de futebol!",
    "Obrigado por ser um mentor incrível.",
    "Para o melhor professor do mundo, Feliz Dia do professor! Obrigado por tudo!"
];

export default frase;